[build]
  functions = "functions"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/api/:splat'
  status = 200

[[redirects]]
  from = '/api/product/*'
  to = '/.netlify/functions/api/product/:splat'
  status = 200